project/models.py
from .database import Base
from flask_security import UserMixin, RoleMixin
from sqlalchemy import create_engine
from sqlalchemy.orm import relationship, backref
from sqlalchemy import Boolean, DateTime, Column, Integer, \
                    String, ForeignKey, UnicodeText

class RolesUsers(Base):
    __tablename__ = 'roles_users'
    id = Column(Integer(), primary_key=True)
    user_id = Column('user_id', Integer(), ForeignKey('user.id'))
    role_id = Column('role_id', Integer(), ForeignKey('role.id'))

class Role(Base, RoleMixin):
    __tablename__ = 'role'
    id = Column(Integer(), primary_key=True)
    name = Column(String(80), unique=True)
    description = Column(String(255))
    permissions = Column(UnicodeText)

class User(Base, UserMixin):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    email = Column(String(255), unique=True)
    username = Column(String(255), unique=True, nullable=True)
    password = Column(String(255), nullable=False)
    last_login_at = Column(DateTime())
    current_login_at = Column(DateTime())
    last_login_ip = Column(String(100))
    current_login_ip = Column(String(100))
    login_count = Column(Integer)
    active = Column(Boolean())
    fs_uniquifier = Column(String(255), unique=True, nullable=False)
    confirmed_at = Column(DateTime())
    roles = relationship('Role', secondary='roles_users',
                         backref=backref('users', lazy='dynamic'))

project/app.py
import os
import sys
import string
import random
import uuid

from flask import Flask, session, render_template_string, render_template, redirect, url_for, flash, request, current_app
from flask_security import Security, current_user, auth_required, hash_password, SQLAlchemySessionUserDatastore
from flask_login import login_user, logout_user
from flask_font_awesome import FontAwesome

from flask_dance.contrib.google import make_google_blueprint, google
from urllib.parse import urlencode

from flask_mailman import Mail
from werkzeug.middleware.proxy_fix import ProxyFix
from werkzeug.security import generate_password_hash

from .config import Config, ProductionConfig, DevelopmentConfig
from dotenv import load_dotenv

from .database import init_db
from .models import User, Role

from .views import views_bp
from .airtableget import airtable_bp

fa = FontAwesome()
#debug_mode = False

def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config['MAX_CONTENT_LENGTH'] = 20 * 1024 * 1024
    
    if "--debug" in sys.argv:
        app.config.from_object(DevelopmentConfig)
        print("Debug Mode " + str(app.config['DEBUG']))
        #debug_mode = False
    else:
        app.config.from_object(ProductionConfig)
        print("Debug Mode " + str(app.config['DEBUG']))
        google_blueprint = create_google_blueprint(app)
        app.register_blueprint(google_blueprint, url_prefix="/login")
        #debug_mode = False

    @app.context_processor
    def context_processor():
        google_login_url = False
        def google_login_url():
            if app.debug:
                print("sorry, in debug mode, no google login available")
                return None
            return url_for("google.login")
        return dict(google_login_url=google_login_url)

    global db_session
    with app.app_context():
        db_session = init_db()

    user_datastore = SQLAlchemySessionUserDatastore(db_session, User, Role)
    app.security = Security(app, user_datastore)

    mail = Mail(app)
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_prefix=1)
    app.register_blueprint(views_bp)
    app.register_blueprint(airtable_bp)

    with app.app_context():
        create_users(app, user_datastore)
        fa.init_app(app)
    
    define_routes(app)
    return app

def define_routes(app):
    @app.route('/authorized')
    def authorized():
        if app.config['DEBUG'] == True:
            return "Not available in development mode", 404
        if not google.authorized:
            return redirect(url_for("google.login"))
        resp = google.get("/oauth2/v3/tokeninfo")
        if not resp.ok:
            flash("Failed to authenticate with Google.", "danger")
            return redirect(url_for("views.home"))

        idinfo = resp.json()
        email = idinfo['email']
        if 'name' in idinfo:
            name = idinfo['name']
        else:
            name = email

        def is_email_authorized(email):
            for user in app.config['ALLOWED_USERS']:
                if user[0] == email:
                    return True
            return False
        
        if not is_email_authorized(email):
            flash("Your email is not authorized.", "danger")
            return redirect(url_for("views.home"))

        user = app.security.datastore.find_user(email=email)
        if not user:
            random_password = generate_random_password()
            hashed_password = generate_password_hash(random_password, method='sha256')
            user = app.security.datastore.create_user(email=email, username=name, password=hashed_password)
            db_session.commit()
        
        login_user(user)
        session['logged_in_with_google'] = True
        return redirect(url_for("views.home"))
    app.add_url_rule('/authorized', view_func=authorized)


    @app.route("/logout")
    @auth_required()
    def logout():
        logout_user()
        return redirect(url_for("views.home"))

def create_google_blueprint(app):
    google_blueprint = make_google_blueprint(
        client_id=app.config['GOOGLE_OAUTH_CLIENT_ID'],
        client_secret=app.config['GOOGLE_OAUTH_CLIENT_SECRET'],
        scope=["https://www.googleapis.com/auth/userinfo.email", "openid"],
        redirect_url="/authorized",
    )
    return google_blueprint

def generate_random_password(length=12):
    characters = string.ascii_letters + string.digits + string.punctuation
    return ''.join(random.choice(characters) for i in range(length))

def create_users(app, user_datastore):
    for user in app.config['ALLOWED_USERS']:
        useremail, userrole = user
        user_in_db = app.security.datastore.find_user(email=useremail)
        role = app.security.datastore.find_role(userrole)

        if not role:
            role = user_datastore.create_role(name=userrole)
            db_session.add(role)
            db_session.commit()

        if not user_in_db:
            new_user = app.security.datastore.create_user(email=useremail, roles=[role], password=generate_password_hash(generate_random_password(), method='sha256'))
            db_session.commit()
    

app = create_app()

if __name__ == "__main__":
    app.run()

project/views.py
# Views

from flask import Blueprint, render_template, redirect, url_for
from flask_security import current_user, auth_required

from .models import User, Role

views_bp = Blueprint('views', __name__)

@views_bp.route('/')
def home():
    return render_template('index.html')


@views_bp.route('/profile')
@auth_required()
def profile():
    if not current_user.is_authenticated:
        return redirect(url_for('security.login'))
    else:
        return render_template('profile.html', name=current_user.email)

''' @app.route('/users', endpoint='users', methods=['GET', 'POST'])
@auth_required
def users():
    form = CreateUserForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('User created successfully!', 'success')
        return redirect(url_for('users'))

    users = User.query.all()

    return render_template('users.html', users=users, form=form) '''

project/templates/airtable/airtable_base.html
{% extends 'base.html' %}

{%- block head_scripts %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/thumbnail.css') }}"/>
{%- endblock head_scripts %}

{% block  styles %} 
{{ super() }}
<style>
.loader-container {
    display: none;
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(255, 255, 255, 0.8);
    z-index: 9999;
  }
  
  .loader {
    border: 16px solid #f3f3f3;
    border-radius: 50%;
    border-top: 16px solid #3498db;
    width: 120px;
    height: 120px;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    -webkit-animation: spin 2s linear infinite;
    animation: spin 2s linear infinite;
  }
  
  @-webkit-keyframes spin {
    0% { -webkit-transform: rotate(0deg); }
    100% { -webkit-transform: rotate(360deg); }
  }
  
  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
</style>  
{% endblock styles %} 


{% block content %}
{% endblock %}

{% block footer -%} 
{% include "airtable/partials/footer.html" %}
{%- endblock footer %}

{% block scripts %} 
{{ super() }}
<script src="{{ url_for('static', filename='js/attachment.js') }}"></script>
<script src="{{ url_for('static', filename='js/edit_form.js') }}"></script>
{% endblock scripts %}

project/templates/airtable/dashboard.html
{% extends 'airtable_base.html' %}

{% block content %}
{{ super() }}
<div class="column">
    <h2 class="title">Tableau de bord</h1>
</div>
{% endblock %}

project/templates/airtable/edit_record.html
{% extends 'airtable_base.html' %}

{% block content %}
{{ super() }}
<h2>Edit Inscription Record</h2>
<form method="POST">
    <label for="name">Name</label>
    <input id="name" name="name" value="{{ record.fields.Name }}" required><br><br>

    <label for="notes">Notes</label>
    <textarea id="notes" name="notes">{{ record.fields.Notes }}</textarea><br><br>

    <label for="status">Status</label>
    <select id="status" name="status">
        {% set status_options = ['Todo', 'In progress', 'Done'] %}
        {% for option in status_options %}
        <option value="{{ option }}" {% if option == record['fields']['Status'] %}selected{% endif %}>{{ option }}</option>
        {% endfor %}
    </select><br><br>
    

    <label for="atelier">Atelier</label>
    <select id="atelier" name="atelier">
        {% for option in field_options['Atelier'] %}
        <option value="{{ option }}" {% if option == record['fields']['atelier'][0] %}selected{% endif %}>{{ field_options['Atelier'][option].get('Name') }}</option>
        {% endfor %}
    </select><br><br>

    <label for="mentors">Mentors</label>
    <div class="control">
        <div class="select is-multiple">
            <select id="mentors" name="mentors" multiple>
                {% for option in field_options['Mentors'] %}
                <option value="{{ option }}" {% if option in record['fields']['mentors'] %}selected{% endif %}>{{ field_options['Mentors'][option].get('Name') }}</option>
                {% endfor %}
            </select>
        </div>
    </div><br><br>
    

    <input type="submit" value="Submit">
</form>
{% endblock %}

project/templates/airtable/form.html
{% extends "airtable_base.html" %}
{% block content %}
{{ super() }}
    <h1>Questionnaire final de sortie du Passe Numérique</h1>
    <form action="{{ url_for('airtable.create_record') }}" method="POST">
        <label for="name">Prénom et Nom *</label>
        <input type="text" id="name" name="name" required><br><br>

        <label for="name">Notes</label>
        <input type="text" id="notes" name="notes" required><br><br>

        <label for="status">Status</label>
        <select id="status" name="status">
            <option>Todo</option>
            <option>In progress</option>
            <option>Done</option>
        </select><br><br>

        <label for="atelier">Atelier</label>
        <select id="atelier" name="atelier">
            {% for option in field_options['Atelier'] %}
            <option value="{{ option }}">{{ field_options['Atelier'][option].get('Name') }}</option>
            {% endfor %}
        </select><br><br>

        <label for="mentors">Mentors</label>
        <div class="control">
            <div class="select is-multiple">
                <select id="mentors" name="mentors" multiple>
                    {% for option in field_options['Mentors'] %}
                    <option value="{{ option.id }}" {% if option.id in record['fields']['mentors'] %}selected{% endif %}>{{ option.fields['Name'] }}</option>
                    {% endfor %}
                </select>
            </div>
        </div><br><br>


        <label for="completed">As-tu terminé le Passe Numérique jusqu'au bout ? *</label>
        <input type="text" id="completed" name="completed" required><br><br>

        <label for="result">Résultat à la sortie de l'opération *</label>
        <select id="result" name="result">
            <option>result 1</option>
            <option>result 2</option>
        </select><br><br>

        <label for="level">Choisi le niveau que tu penses avoir atteint à la fin du Passe Numérique : *</label>
        <select id="level" name="level">
            <option>level 1</option>
            <option>level 2</option>
        </select><br><br>

        <label for="story">Peux-tu me parler de ton parcours ?</label>
        <textarea id="story" name="story"></textarea><br><br>

        <input type="submit" value="Submit">
    </form>
{% endblock %}

project/templates/airtable/modules/modules.html
{% extends 'airtable_base.html' %}

{% block content %}
{{ super() }}

    <div class="column is-9">
        <section class="section">
            <div class="container">
                <h2 class="title">Suivi des modules</h2>
                <table class="table is-bordered is-striped is-hoverable is-fullwidth">
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Session</th>
                            <th>Intervenant</th>
                            <th>Participants</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for record in records %}
                        <tr>
                            <td>{{ record['fields']['Name'] }}</td>
                            <td>{{ (sessions.get(record['fields']['Session'][0]) if 'Session' in record['fields'] else {}).get('fields', {}).get('Name')|default('Not Available') }}</td>
                            <td>
                            {% if record['fields']['Intervenants'] %}
                            {% for intervenant in record['fields']['Intervenants'] %}
                                {{ intervenants.get(intervenant)['fields']['Name']}}
                            {% endfor %}
                            {% endif %}
                            </td>
                            <td>
                            {% if record['fields']['Participants'] %}
                            {% for participant in record['fields']['Participants'] %}
                                {{ participants.get(participant)['fields']['Nom complet']}}
                            {% endfor %}
                            {% endif %}
                            </td>
                            <td>
                                <a class="button is-small is-primary" href="{{ url_for('airtable.show_workshops', module_id=record['id']) }}">Séances</a>
                            </td>
                        </tr>      
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
    </div>
{% endblock %}

project/templates/airtable/partials/footer.html
{% block navbar %}
<nav class="tabs is-boxed is-medium is-centered">
      <ul>
        <li class="{{ 'is-active' if request.path == '/dashboard' else '' }}">
          <a href="/dashboard">Tableau de bord</a>
        </li>
        <li class="{{ 'is-active' if request.path == '/participants' else '' }}">
          <a href="/participants">Participants</a>
        </li>
        <li class="{{ 'is-active' if request.path == '/modules' else '' }}">
          <a href="/modules">Modules</a>
        </li>
        <li class="{{ 'is-active' if request.path == '/my_mentorat' else '' }}">
          <a href="/my_mentorat">Mentorat</a>
        </li>
        <li class="{{ 'is-active' if request.path == '/sessions' else '' }}">
          <a href="/sessions">Sessions</a>
        </li>
      </ul>
  </nav>
{% endblock %}

project/templates/airtable/participants/participant_dashboard.html
{% extends 'airtable_base.html' %}

{% block content %}
{{ super() }}

<div class="column is-9">
    <section class="section">
        <div class="container">
            <h2 class="title">Dashboard pour {{ participant['fields']['Nom complet']}}</h2>
            <h3>Sessions</h3>
            <ul>
            {% for session in sessions %}
                <li>{{ session.fields.Name }}</li>
            {% endfor %}
            </ul>
            <h3>Formations<h3>
            <ul>
                {% for formation in formations %}
                    <li>{{ formation.fields.Name }}</li>
                {% endfor %}
            </ul>
        </div>
    </section>
</div>

{% endblock %}

project/templates/airtable/participants/participant_profile.html
{% extends 'airtable_base.html' %}

{% block content %}
<div class="column is-three-quarters-desktop  box  is-centered has-text-centered">

    <h2 class="title">Edit Participant</h2>
    <form method="POST" enctype="multipart/form-data" id="detailsForm{{ record.id }}">
        <div class="field is-horizontal">
            <div class="field-label is-normal">
                <label class="label" for="family_name">Nom de famille</label>
            </div>
            <div class="field-body has-text-left">
                <div class="field">                
                    <div class="control">
                        <input id="family_name" name="family_name" value="{{ record.fields['Nom de famille'] }}" required readonly><br><br>
                    </div>
                </div>
            </div>
        </div>
        <div class="field is-horizontal">
            <div class="field-label is-normal">
                <label class="label" for="first_name">Prénom</label>
            </div>
            <div class="field-body has-text-left">
                <div class="field">
                    <div class="control">
                        <input id="first_name" name="first_name" value="{{ record.fields.Prénom }}" required readonly><br><br>
                    </div>
                </div>
            </div>
        </div>

        <div class="field is-horizontal">
            <div class="field-label is-normal">
                <label class="label">CNI</label>
            </div>
            <div class="field-body">
                <div class="field">
                    <div class="control">
                        <div class="columns is-multiline" id="CNI-columns">
                            <div class="column is-one-quarter">
                                <div class="card">
                                    <div class="card-image">
                                    </div>
                                    <div class="card-footer">
                                        <div class="button card-footer-item" id="add-image-label-CNI" data-field="CNI" data-columns-container="CNI-columns">Add</div>
                                    </div>
                                </div>
                            </div>
                            {% for attachment in record.fields.CNI %}
                            <div class="column is-one-quarter">
                                <div class="card">
                                    <div class="card-image">
                                        <figure class="image is-4by3">
                                            <a href="{{ attachment.url }}" target="_blank">
                                                <img class="thumbnail" id="thumbnail_CNI_{{ attachment.id }}" src="{{ attachment.thumbnails.large.url }}"></img>
                                                <img id="red_cross_CNI_{{ attachment.id }}" src="{{ url_for('static', filename='svg/full-cross-circle-alt-svgrepo-com.svg')}}" alt="Red Cross" style="display: none;">
                                            </a>
                                        </figure>
                                    </div>
                                    <div class="card-footer">
                                        <div class="button card-footer-item existing-remove-label" id="remove_label_CNI_{{ attachment.id }}" data-field="CNI" data-attachment-id="{{ attachment.id }}">Remove</div>
                                    </div>
                                    <input type="file" name="CNI_{{ attachment.id }}" id="CNI_{{ attachment.id }}" field-data="CNI" value="{{ attachment.url }}" style="display: none;">
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="field is-horizontal">
            <div class="field-label is-normal">
                <label class="label">Attestation Pôle Emploi</label>
            </div>
            <div class="field-body">
                <div class="field">
                    <div class="control">
                        <div class="columns is-multiline" id="Attestation-columns">
                            <div class="column is-one-quarter">
                                <div class="card">
                                    <div class="card-image">
                                    </div>
                                    <div class="card-footer">
                                        <div class="button card-footer-item" id="add-image-label-Attestation" data-field="Attestation" data-columns-container="Attestation-columns">Add</div>
                                    </div>
                                </div>
                            </div>
                            {% for attachment in record.fields['Attestation Pôle Emploi'] %}
                            <div class="column is-one-quarter">
                                <div class="card">
                                    <div class="card-image">
                                        <figure class="image is-4by3">
                                            <a href="{{ attachment.url }}" target="_blank">
                                                <img class="thumbnail" id="thumbnail_Attestation_{{ attachment.id }}" src="{{ attachment.thumbnails.large.url }}"></img>
                                                <img id="red_cross_Attestation_{{ attachment.id }}" src="{{ url_for('static', filename='svg/full-cross-circle-alt-svgrepo-com.svg')}}" alt="Red Cross" style="display: none;">
                                            </a>
                                        </figure>
                                    </div>
                                    <div class="card-footer">
                                        <div class="button card-footer-item existing-remove-label" id="remove_label_Attestation_{{ attachment.id }}" data-field="Attestation" class="card-footer-item" data-attachment-id="{{ attachment.id }}">Remove</div>
                                    </div>
                                    <input type="file" name="Attestation_{{ attachment.id }}" id="Attestation_{{ attachment.id }}" field-data="Attestation"  value="{{ attachment.url }}" style="display: none;">
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="control center">
            <button class="button is-link" type="submit" id="saveButton{{ record.id }}" style="display: none;">Save</button>
        </div>
    </form>
    <div class="control">      
        <button class="button is-link" id="editButton{{ record.id }}">Edit</button>
    </div>
    
</div>
{% endblock %}

project/templates/airtable/participants/participants_list.html
{% extends 'airtable_base.html' %}

{% block content %}
<div class="columns is-multiline">
{% for record in records %}
<div class="column is-one-third">
    <div class="card m-4">
        <div class="card-content">
            <div class="media">
                <div class="media-left">
                    <figure class="image is-128x128">
                        <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                    </figure>
                </div>
                <div class="media-content mt-4">
                    <p class="title is-4 has-text-black">{{ record['fields']['Nom complet'] }}</p>
                </div>
            </div>
        
            <div class="content">
                <p>{{ record['fields']['Adresse complète'] }}</p>
                <p>{{ record['fields']['Date de naissance'] }}</p>
                <p>{{ record['fields']['Sexe'] }}</p>
                {% for attachment in record['fields']['CNI'] %}
                <a href="{{ attachment['url']}}" ><img src="{{ attachment['thumbnails']['small']['url']}}"></img></a>
                {% endfor %}
            </div>
        </div>
        <footer class="card-footer center">
            <a class="button" href="{{ url_for('airtable.participant_profile', participant_id = record['id'])}}">Fiche</a>
            <a class="button" href="{{ url_for('airtable.participant_dashboard', participant_id = record['id'])}}">Dashboard</a>
        </footer>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}

project/templates/airtable/submitted.html
{% extends "airtable_base.html" %}
{% block content %}
{{ super() }}
<h1>Your form has been submitted successfully!</h1>
<a href="{{ url_for('airtable.create_record') }}">Submit another response</a>
{% endblock %}

project/templates/airtable/workshops/individual_report.html
{% extends 'airtable_base.html' %}

{% block content %}
{{ super() }}

<div class="column is-12 is-9-fullhd">
    <section class="section">
        <div class="container">
            <h2 class="title">Évaluation de l'étudiant {{ participant['fields']['Nom complet'] }} pour la séance {{ workshop['fields']['Index'] }} du module {{ module_base['fields']['Name'] }} ( le {{ workshop.fields.Date }} )</h2>
            <form id="evalForm{{ workshop['id'] }}-{{ participant['id'] }}" action="{{ url_for('airtable.show_workshop_individual_report', module_id=module['id'], workshop_id=workshop['id'], participant_id=participant['id']) }}" method="POST">
            
                <div class="field">
                    <label class="label">Commentaire</label>
                    <div class="control">
                        <input classe="input" type="text" name="Commentaire" value="{{ report['fields']['Commentaire']}}" readonly />
                    </div>
                </div>
                <div class="control">
                    <button class="button is-link" type="submit" id="saveButton{{ workshop['id'] }}-{{ participant['id'] }}" style="display: none;">Save</button>
                </div>
            </form>
            <div class="control">      
                <button class="button is-link" id="editButton{{ workshop['id'] }}-{{ participant['id'] }}">Edit</button>
            </div>
        </div>
    </section>
</div>

{% endblock %}

project/templates/airtable/workshops/workshop.html
{% extends 'airtable_base.html' %}

{% block content %}
{{ super() }}

<div class="column is-9">
    <section class="section">
        <div class="container">
            <h2 class="title">Séance {{ workshop['fields']['Index'] }} pour le module {{ module_base['fields']['Name'] }}</h2>
                <form id="detailsForm{{ workshop['id'] }}" action="{{ url_for('airtable.show_workshop', module_id=module['id'], workshop_id=workshop['id']) }}" method="POST">
                    <div class="field">
                        <label class="label">Date</label>
                        <div class="control">
                            <input class="input" type="date" name="Date", value="{{ workshop['fields']['Date'] }}" readonly />
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Commentaire</label>
                        <div class="control">
                            <input classe="input" type="text" name="Commentaire" value="{{ workshop['fields']['Commentaire']}}" readonly />
                        </div>
                    </div>
                    <div class="control">
                        <button class="button is-link" type="submit" id="saveButton{{ workshop['id'] }}" style="display: none;">Save</button>
                    </div>
                </form>
                <div class="control">      
                    <button class="button is-link" id="editButton{{ workshop['id'] }}">Edit</button>
                    <a class="button is-link" href="{{ url_for('airtable.presences_workshop', module_id=module.id, workshop_id = workshop.id) }}">Présences / Évaluation</a>
                </div>
        </div>
    </section>
</div>

{% endblock %}

project/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="column is-half">
    <h1 class="title">
      Flask Login Example
    </h1>
    <h2 class="subtitle">
      Easy authentication and authorization in Flask.
    </h2>
</div>
{% endblock %}

project/templates/partials/navbar.html
{% block navbar %}
<nav class="navbar" role="navigation">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item">
                <img src="https://bulma.io/images/bulma-type-white.png" alt="Logo">
              </a>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">
                <a href="{{ url_for('views.home') }}" class="navbar-item">
                    Home
                </a>
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('views.profile') }}" class="navbar-item">
                    Profile
                </a>
                <a href="{{ url_for('airtable.airtable_dashboard') }}" class="navbar-item">
                    Airtable
                </a>
                
                <a href="{{ url_for('security.logout') }}" class="navbar-item">
                    Logout
                </a>
                {% endif %}
                {% if not current_user.is_authenticated %}
                <a href="{{ url_for('security.login') }}" class="navbar-item">
                    Login
                </a>               
                {% endif %} 
            </div>
        </div>
    </div>
</nav>
{% endblock %}

project/templates/profile.html
{% extends "base.html" %}
{% block content %}
<div class="hero-body">
    <div class="container has-text-centered">
        <h1>Hello {{name}}</h1>
    </div>
</div>
{% endblock %}